### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by Q-Sharp**
here you go

Just add following secrets to github actions:

UNITY_EMAIL
UNITY_PASSWORD

# Use for paid version:
UNITY_SERIAL

# Use for free version:
UNITY_LICENSE

### CODE REVIEW

**Comment by Greenfoot5** [comment]
Currently waiting for a reply on Unity as to which license we're allowed to use.

**Comment by Q-Sharp** [comment]
Any news?

**Comment by Greenfoot5** [comment]
Sadly, no. I asked last Monday, and they said it could take 10 days as they had quite a few requests to work through, so hopefully sometime this week.

If they don't, I'll merge and setup with the free license.

**Comment by Greenfoot5** [comment]
As the project doesn't make any money, I may use my educational license.

**Pull request merged**
